#!/usr/bin/env python3
"""Turn the OpenStreetMap fetch around the house into a JS module of local metre coords.

The house at 7821 SE Mammoth Dr is the origin. Everything is metres from it,
x east and z south, so Three.js can use the numbers directly.
"""
import json
import math
import os

SRC = "/opt/data/state/game/hobe-house-area.json"
OUT = "/opt/data/workspace/hobe-walk/src/data/streets.js"

# The house, resolved by the US Census geocoder on 2026-10-05.
LAT0 = 27.104196675805
LON0 = -80.181603162067

M_PER_DEG_LAT = 110574.0
M_PER_DEG_LON = 111320.0 * math.cos(math.radians(LAT0))


def to_local(lat, lon):
    """Metres from the house. x east, z south, matching Three.js ground axes."""
    x = (lon - LON0) * M_PER_DEG_LON
    z = -(lat - LAT0) * M_PER_DEG_LAT
    return round(x, 2), round(z, 2)


d = json.load(open(SRC))
els = d.get("elements", [])

roads, water, greens, places = [], [], [], []

for e in els:
    t = e.get("tags", {})
    geom = e.get("geometry") or []
    if not geom and "lat" in e:
        geom = [{"lat": e["lat"], "lon": e["lon"]}]
    if len(geom) < 2:
        continue
    pts = [to_local(g["lat"], g["lon"]) for g in geom]

    if t.get("highway"):
        roads.append({
            "name": t.get("name") or "",
            "kind": t.get("highway"),
            "pts": pts,
        })
    elif t.get("natural") == "water" or t.get("waterway"):
        water.append({"pts": pts})
    elif t.get("landuse") == "grass" or t.get("leisure") == "park" or t.get("leisure") == "pitch":
        greens.append({"pts": pts})
    elif t.get("place") or t.get("amenity"):
        places.append({"name": t.get("name") or "", "pt": pts[0]})

body = f"""// Generated by tools/build_streets.py - do not edit by hand.
// Source: OpenStreetMap, fetched 2026-10-05, 1200 m around 7821 SE Mammoth Dr.
// Origin: the house, at {LAT0}, {LON0}. Coordinates are metres, x east and z south.

export const ORIGIN = {{ lat: {LAT0}, lon: {LON0} }};
export const AREA_RADIUS = 620;

export const ROADS = {json.dumps(roads, separators=(',', ':'))};

export const WATER = {json.dumps(water, separators=(',', ':'))};

export const GREENS = {json.dumps(greens, separators=(',', ':'))};

export const PLACES = {json.dumps(places, separators=(',', ':'))};
"""

os.makedirs(os.path.dirname(OUT), exist_ok=True)
open(OUT, "w").write(body)

named = sorted({r["name"] for r in roads if r["name"]})
print(f"  roads written   : {len(roads)}")
print(f"  named roads     : {len(named)}")
print(f"  water shapes    : {len(water)}")
print(f"  green shapes    : {len(greens)}")
print(f"  named places    : {len(places)}")
print(f"  module          : {OUT} ({len(body)} bytes)")
xs = [p[0] for r in roads for p in r["pts"]]
zs = [p[1] for r in roads for p in r["pts"]]
print(f"  extent          : x {min(xs):.0f} to {max(xs):.0f} m, z {min(zs):.0f} to {max(zs):.0f} m")
