#!/usr/bin/env python3
"""Fetch the real building footprints around the house and write them as local metres.

The street data gave us roads. This gives us the houses that stand on them, so the
world can draw the actual shapes of the buildings on this block instead of a row of
identical boxes.

Source: OpenStreetMap building footprints around 7821 SE Mammoth Dr, most of which
carry source=microsoft/BuildingFootprints. They carry outlines but no heights and no
house numbers, so the height is derived from the size of the footprint: a bigger
building on this block is a bigger house, not a taller one, but a little height
variation stops a street of flat roofs reading as a car park.

Output: src/data/buildings.js
"""
import json
import math
import os
import time
import urllib.error
import urllib.parse
import urllib.request

LAT0 = 27.104196675805
LON0 = -80.181603162067
RADIUS = 700            # metres around the house to fetch
OUT = "/opt/data/workspace/hobe-walk/src/data/buildings.js"
RAW = "/opt/data/state/game/hobe-buildings-raw.json"

M_PER_DEG_LAT = 110574.0
M_PER_DEG_LON = 111320.0 * math.cos(math.radians(LAT0))
HOSTS = [
    "https://overpass-api.de/api/interpreter",
    "https://overpass.kumi.systems/api/interpreter",
    "https://overpass.openstreetmap.ru/api/interpreter",
]


def to_local(lat, lon):
    """Metres from the house. x east, z south, matching Three.js ground axes."""
    return round((lon - LON0) * M_PER_DEG_LON, 2), round(-(lat - LAT0) * M_PER_DEG_LAT, 2)


def area_of(pts):
    """Shoelace area in square metres. Absolute, so winding does not matter."""
    a = 0.0
    for i in range(len(pts)):
        x0, z0 = pts[i]
        x1, z1 = pts[(i + 1) % len(pts)]
        a += x0 * z1 - x1 * z0
    return abs(a) / 2.0


def fetch():
    query = ("[out:json][timeout:180];"
             f'way["building"](around:{RADIUS},{LAT0},{LON0});'
             "out geom;")
    body = urllib.parse.urlencode({"data": query}).encode()
    last = None
    for attempt in range(4):
        for host in HOSTS:
            try:
                req = urllib.request.Request(host, data=body,
                                             headers={"User-Agent": "ApolloAgent/1.0 hobe-walk"})
                raw = urllib.request.urlopen(req, timeout=180).read()
                data = json.loads(raw)
                os.makedirs(os.path.dirname(RAW), exist_ok=True)
                open(RAW, "wb").write(raw)
                print(f"  fetched from {host.split('/')[2]}: {len(data.get('elements', []))} ways")
                return data
            except Exception as e:
                last = f"{host.split('/')[2]}: {str(e)[:70]}"
                print(f"    {last}")
        time.sleep(8)
    raise SystemExit(f"  every Overpass host failed, last: {last}")


def main():
    data = fetch()
    buildings = []
    skipped_open = skipped_tiny = 0
    for e in data.get("elements", []):
        geom = e.get("geometry") or []
        if len(geom) < 4:
            continue
        pts = [to_local(g["lat"], g["lon"]) for g in geom]
        # Overpass repeats the first point to close the ring. Drop the repeat.
        if pts[0] == pts[-1]:
            pts = pts[:-1]
        if len(pts) < 3:
            skipped_open += 1
            continue
        a = area_of(pts)
        if a < 18:                 # a shed or a carport, not a house
            skipped_tiny += 1
            continue
        # A one storey Florida ranch: walls a little over three metres, a shallow
        # roof. Bigger footprint reads slightly taller and slightly taller roofed.
        wall = round(3.05 + min(1.15, a / 240.0), 2)
        rise = round(0.95 + min(0.75, a / 420.0), 2)
        buildings.append({"a": round(a), "w": wall, "r": rise, "pts": pts})

    body = (f"// Generated by tools/build_buildings.py - do not edit by hand.\n"
            f"// Source: OpenStreetMap building footprints within {RADIUS} m of "
            f"7821 SE Mammoth Dr, fetched 2026-10-06.\n"
            f"// Origin and axes as in streets.js: metres, x east and z south.\n"
            f"// a footprint area in square metres, w wall height, r roof rise.\n\n"
            f"export const BUILDINGS = "
            f"{json.dumps(buildings, separators=(',', ':'))};\n")
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, "w").write(body)

    areas = sorted(b["a"] for b in buildings)
    print(f"  buildings written : {len(buildings)}")
    print(f"  skipped, too small: {skipped_tiny}   unclosed: {skipped_open}")
    if areas:
        print(f"  footprint area    : min {areas[0]} m2, median {areas[len(areas)//2]} m2, max {areas[-1]} m2")
        print(f"  wall height       : {min(b['w'] for b in buildings)} to {max(b['w'] for b in buildings)} m")
    xs = [p[0] for b in buildings for p in b["pts"]]
    zs = [p[1] for b in buildings for p in b["pts"]]
    if xs:
        print(f"  extent            : x {min(xs):.0f} to {max(xs):.0f} m, z {min(zs):.0f} to {max(zs):.0f} m")
    print(f"  module            : {OUT} ({len(body)} bytes)")


if __name__ == "__main__":
    main()
